# Generated by Django 5.2.7 on 2026-03-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=50)),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("area", models.CharField(max_length=50)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("condo", "Condominium"),
                            ("townhouse", "Townhouse"),
                            ("villa", "Villa"),
                        ],
                        default="house",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
